# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code from the repository

    - name: Set up Go
      uses: actions/setup-go@v2  # Set up Go environment
      with:
        go-version: '1.22'  # Specify the Go version you are using

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
